# Generated by Django 3.2.9 on 2022-03-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='car_id',
            new_name='car',
        ),
    ]
